# Generated by Django 4.0.4 on 2022-09-21 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/')),
                ('seller_addr', models.CharField(max_length=42)),
                ('category', models.IntegerField(choices=[(0, '721'), (1, '1155')])),
                ('product_id', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=250)),
                ('amount', models.IntegerField()),
                ('buy_it_now', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('add_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('latest_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('auction_time', models.DecimalField(decimal_places=2, max_digits=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starting_time', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, '拍賣中'), (1, '結束拍賣'), (2, '即將拍賣')], default=2)),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('etherscan_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('status_deploy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Auction_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_addr', models.CharField(max_length=42)),
                ('auction_id', models.CharField(max_length=250)),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direct_Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/')),
                ('seller_addr', models.CharField(max_length=42)),
                ('category', models.IntegerField(choices=[(0, '721'), (1, '1155')])),
                ('product_id', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=250)),
                ('starting_time', models.DateTimeField(null=True)),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('auction_time', models.DecimalField(decimal_places=2, max_digits=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, '拍賣中'), (1, '結束拍賣'), (2, '即將拍賣')], default=2)),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('etherscan_url', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ERC1155',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=42)),
                ('erc721_id', models.CharField(max_length=42)),
                ('erc1155_id', models.CharField(max_length=250)),
                ('erc1155_name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='image/')),
                ('amount', models.IntegerField()),
                ('etherscan_url', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ERC721',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=42)),
                ('erc721_id', models.CharField(max_length=250)),
                ('erc721_name', models.CharField(max_length=250)),
                ('symbol', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='image/')),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('etherscan_url', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundraisingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan721_id', models.CharField(max_length=255)),
                ('initiator_addr', models.CharField(max_length=42)),
                ('title', models.CharField(max_length=255)),
                ('threshold_amount', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('fundraising_start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fundraising_end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('execution_start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('execution_end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('profitsharing_investor', models.IntegerField()),
                ('profitsharing_initiator', models.IntegerField()),
                ('profitsharing_platform', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('current_money', models.IntegerField(default=0)),
                ('img', models.CharField(blank=True, max_length=2048, null=True)),
                ('status', models.IntegerField(choices=[(0, '募資中'), (1, '執行計畫'), (2, '關閉')], default=0)),
                ('liquidation_time', models.IntegerField(default=30)),
                ('product_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liquidation_discount', models.IntegerField(default=0)),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('etherscan_url', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_addr', models.CharField(max_length=42)),
                ('plan_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('etherscan_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='invest', max_length=255)),
                ('invest_token_url', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_addr', models.CharField(max_length=42)),
                ('title', models.CharField(max_length=50)),
                ('plan721_id', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('product_id', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=255)),
                ('issued_amount', models.IntegerField(default=0)),
                ('sold_amount', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('img', models.CharField(blank=True, max_length=2048, null=True)),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('etherscan_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('product_1155_id', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_addr', models.CharField(max_length=42)),
                ('plan721_id', models.IntegerField()),
                ('product1155_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('etherscan_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_address', models.CharField(max_length=42)),
                ('platform_token', models.FloatField(default=0)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
